# reference
# profiles/N100_s0.jl
# # standard case, no selection 
# # N ≈ 500
# g₀ = Genotype(
#     1, # id
#     Int(1e6),  # total synonymous mutations
#     Int(1e4),  # total APOBEC3 mutations
#     Int(1e4),  # total reverse APOBEC3 mutations
#     0,  # synonymous mutations
#     0,  # APOBEC3 mutations
#     0  # reverse APOBEC3 mutations
#    )
#    Par = Parameters(
#    1.0,  # β₀
#    0.5,  # μ₀
#    0.0,  # s
#    [1e-7, 1e-5, 1e-6],  # δ
#    t -> minimum([1e3 ,1e2 * (1+exp(0.01t))])  # K
# )

# this code generates the profiles for given N and s and writes into the profiles folder
# the profiles are generated by the function generate_profile

function generate_profile(N, s)
    return """
# N = $N
g₀ = Genotype(
    1, # id
    Int(1e6),  # total synonymous mutations
    Int(1e4),  # total APOBEC3 mutations
    Int(1e4),  # total reverse APOBEC3 mutations
    0,  # synonymous mutations
    0,  # APOBEC3 mutations
    0  # reverse APOBEC3 mutations
   )
   Par = Parameters(
   1.0,  # β₀
   0.5,  # μ₀
   $s,  # s
   [1e-7, 1e-5, 1e-6],  # δ
   t -> minimum([$(10N) ,$(N) * (1+exp(0.01t))])  # K
)
"""
end

Ns = [100, 500, 1000, 5000, 10000]
ss = [0.0, 0.1, 1, 10, 100]

for N in Ns
    for s in ss
        open("profiles/N$(N)_s$(s).jl", "w") do f
            write(f, generate_profile(N, s))
        end
    end
end